INSERT INTO site_settings (key, value) VALUES
('privacy_title', 'Privacy Policy'),
('privacy_body', E'KYROO operates the KYROO platform. This Privacy Policy explains how we collect, use, and protect your personal data in accordance with the EU General Data Protection Regulation (GDPR).\n\n1. Data Controller\nKYROO\nSchoenhauser Allee 100\n10119 Berlin, Germany\nE-Mail: info@kyroo.de\n\n2. Data We Collect\n- Account data: email address, name, password (hashed)\n- Subscription data: plan type, payment method (last 4 digits only), billing history\n- Usage data: pages visited, articles read, preferences\n- Newsletter: email address and subscription date\n- Technical data: IP address, browser type, device info (via server logs)\n\n3. How We Use Your Data\n- To provide and improve the KYROO platform\n- To process payments and manage subscriptions\n- To send newsletters you have opted into\n- To analyze usage patterns and improve content\n- To comply with legal obligations\n\n4. Legal Basis (GDPR Art. 6)\n- Contract performance: account management, subscriptions\n- Legitimate interest: analytics, platform improvement\n- Consent: newsletter, marketing communications\n\n5. Data Sharing\nWe do not sell your data. We share data only with:\n- Payment processors (for transaction processing)\n- Hosting providers (for infrastructure)\n- Analytics tools (anonymized data only)\n\n6. Data Retention\n- Account data: retained while your account is active, deleted within 30 days of account deletion\n- Payment records: retained for 10 years (German tax law)\n- Newsletter data: retained until you unsubscribe\n- Server logs: deleted after 90 days\n\n7. Your Rights\nUnder GDPR, you have the right to:\n- Access your personal data\n- Rectify inaccurate data\n- Erase your data (right to be forgotten)\n- Restrict processing\n- Data portability\n- Object to processing\n- Withdraw consent at any time\n\nTo exercise these rights, contact us at info@kyroo.de.\n\n8. Cookies\nWe use only essential cookies required for authentication and session management. No tracking cookies are used.\n\n9. Changes\nWe may update this policy. Changes will be posted on this page with an updated date.\n\nLast updated: March 2026'),

('terms_title', 'Terms of Service'),
('terms_body', E'Welcome to KYROO. By using our platform, you agree to these Terms of Service. Please read them carefully.\n\n1. About KYROO\nKYROO is operated by KYROO, Schoenhauser Allee 100, 10119 Berlin, Germany. KYROO is a discovery and lifestyle platform offering editorial content on trends, AI, fitness, and recommendations.\n\n2. Accounts\n- You must be at least 16 years old to create an account\n- You are responsible for keeping your login credentials secure\n- One account per person\n- We reserve the right to suspend accounts that violate these terms\n\n3. Free Content\nFree articles, trend drops, and recommendations are available to all users at no cost. We reserve the right to change which content is free at any time.\n\n4. KYROO Premium\n- Premium subscriptions are available monthly (6 EUR/month) or annually (72 EUR/year)\n- Subscriptions auto-renew unless cancelled before the renewal date\n- You can cancel anytime from your account settings\n- Refunds are available within 14 days of initial purchase if no premium content has been accessed\n- Premium content is for personal use only and may not be redistributed\n\n5. Payment\n- Payments are processed securely\n- We accept credit/debit cards, PayPal, and SEPA direct debit\n- All prices include applicable VAT (German VAT: 19%)\n- Failed payments may result in temporary loss of premium access\n\n6. Content\n- All content on KYROO is protected by copyright\n- You may share article links but not reproduce full article text\n- User-generated content (if applicable) must not violate laws or third-party rights\n- We reserve the right to remove content at our discretion\n\n7. AI-Generated Content\nSome articles on KYROO may be generated or assisted by AI. All AI content is reviewed by our editorial team before publication. AI-generated content is clearly the intellectual property of KYROO.\n\n8. Limitation of Liability\nKYROO provides editorial content for informational purposes only. We are not liable for decisions made based on our content, including but not limited to fitness advice, tool recommendations, or trend predictions.\n\n9. Governing Law\nThese terms are governed by the laws of the Federal Republic of Germany. The courts of Berlin have exclusive jurisdiction.\n\n10. Contact\nFor questions about these terms:\nKYROO\nSchoenhauser Allee 100\n10119 Berlin\nE-Mail: info@kyroo.de\n\nLast updated: March 2026')
ON CONFLICT (key) DO NOTHING;

-- Update footer links
UPDATE footer_links SET url = 'privacy' WHERE label = 'Privacy Policy';
UPDATE footer_links SET url = 'terms' WHERE label = 'Terms of Service';
